version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Build SDK
          command: ./gradlew sdk
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_test_results:
          path: player/build/test-results/testReleaseUnitTest